### ISSUE TITLE
ImportError: No module named buildconfig

### ISSUE THREAD

**Issue by arky** [imphil/meta-b2g#1]
Build failed on Ubuntu 13.04 system with "ImportError: No module named buildconfig" . Looks like a virtual environment issue.

make[5]: Entering directory `/media/DevDrive/poky/rpi-build/tmp/work/armv6-vfp-poky-linux-gnueabi/b2g-linuxgl-rpi/dev-r0/mozilla-central/objdir/js/src'
rm -f libjs_static.a libjs_static.a.desc
/usr/bin/python2.7 /media/DevDrive/poky/rpi-build/tmp/work/armv6-vfp-poky-linux-gnueabi/b2g-linuxgl-rpi/dev-r0/mozilla-central/js/src/config/pythonpath.py -I./config /media/DevDrive/poky/rpi-build/tmp/work/armv6-vfp-poky-linux-gnueabi/b2g-linuxgl-rpi/dev-r0/mozilla-central/js/src/config/expandlibs_exec.py --depend .deps/libjs_static.a.pp --target libjs_static.a --extract -- arm-poky-linux-gnueabi-ar cr libjs_static.a jsalloc.o jsanalyze.o jsapi.o jsarray.o jsatom.o jsbool.o jsclone.o jscntxt.o jscompartment.o jsdate.o jsdbgapi.o jsdhash.o jsdtoa.o jsexn.o jsfriendapi.o jsfun.o jsgc.o jscrashreport.o jsinfer.o jsinterp.o jsiter.o jslog2.o jsmath.o jsmemorymetrics.o jsnativestack.o jsnum.o jsobj.o json.o jsonparser.o jsopcode.o jsproxy.o jsprf.o jsprobes.o jspropertycache.o jspropertytree.o jsreflect.o jsscope.o jsscript.o jsstr.o jstypedarray.o jsutil.o jswatchpoint.o jsweakmap.o jsworkers.o ThreadPool.o Monitor.o ForkJoin.o jswrapper.o jsxml.o prmjtime.o sharkctl.o ArgumentsObject.o DateTime.o Debugger.o GlobalObject.o Object.o ObjectImpl.o ScopeObject.o Stack.o String.o BytecodeCompiler.o BytecodeEmitter.o FoldConstants.o Intl.o NameFunctions.o ParallelArray.o ParseMaps.o ParseNode.o Parser.o SPSProfiler.o SelfHosting.o TokenStream.o TestingFunctions.o Profilers.o LifoAlloc.o Eval.o MapObject.o RegExpObject.o RegExpStatics.o RegExp.o RootMarking.o Marking.o Memory.o Statistics.o StoreBuffer.o Iteration.o Verifier.o StringBuffer.o Unicode.o Xdr.o MethodJIT.o StubCalls.o Compiler.o FrameState.o FastArithmetic.o FastBuiltins.o FastOps.o LoopState.o StubCompiler.o MonoIC.o PolyIC.o ImmutableSync.o InvokeHelpers.o Retcon.o TrampolineCompiler.o ExecutableAllocator.o PageBlock.o YarrInterpreter.o YarrPattern.o YarrSyntaxChecker.o YarrCanonicalizeUCS2.o ExecutableAllocatorPosix.o OSAllocatorPosix.o ARMAssembler.o MacroAssemblerARM.o MacroAssemblerX86Common.o YarrJIT.o CTypes.o Library.o jsperf.o pm_linux.o  ctypes/libffi/.libs/libffi.a 
Traceback (most recent call last):
  File "/media/DevDrive/poky/rpi-build/tmp/work/armv6-vfp-poky-linux-gnueabi/b2g-linuxgl-rpi/dev-r0/mozilla-central/js/src/config/pythonpath.py", line 56, in <module>
    main(sys.argv[1:])
  File "/media/DevDrive/poky/rpi-build/tmp/work/armv6-vfp-poky-linux-gnueabi/b2g-linuxgl-rpi/dev-r0/mozilla-central/js/src/config/pythonpath.py", line 48, in main
    execfile(script, frozenglobals)
  File "/media/DevDrive/poky/rpi-build/tmp/work/armv6-vfp-poky-linux-gnueabi/b2g-linuxgl-rpi/dev-r0/mozilla-central/js/src/config/expandlibs_exec.py", line 26, in <module>
    from expandlibs import ExpandArgs, relativize, isObject, ensureParentDir, ExpandLibsDeps
  File "/media/DevDrive/poky/rpi-build/tmp/work/armv6-vfp-poky-linux-gnueabi/b2g-linuxgl-rpi/dev-r0/mozilla-central/js/src/config/expandlibs.py", line 31, in <module>
    import expandlibs_config as conf
  File "/home/arky/src/mozilla-central/js/src/config/expandlibs_config.py", line 5, in <module>
    from buildconfig import substs
ImportError: No module named buildconfig
make[5]: *** [libjs_static.a] Error 1
make[5]: Leaving directory`/media/DevDrive/poky/rpi-build/tmp/work/armv6-vfp-poky-linux-gnueabi/b2g-linuxgl-rpi/dev-r0/mozilla-central/objdir/js/src'
make[4]: **\* [libs_tier_js] Error 2
make[4]: Leaving directory `/media/DevDrive/poky/rpi-build/tmp/work/armv6-vfp-poky-linux-gnueabi/b2g-linuxgl-rpi/dev-r0/mozilla-central/objdir'
make[3]: *** [tier_js] Error 2
make[3]: Leaving directory`/media/DevDrive/poky/rpi-build/tmp/work/armv6-vfp-poky-linux-gnueabi/b2g-linuxgl-rpi/dev-r0/mozilla-central/objdir'
make[2]: **\* [default] Error 2
make[2]: Leaving directory `/media/DevDrive/poky/rpi-build/tmp/work/armv6-vfp-poky-linux-gnueabi/b2g-linuxgl-rpi/dev-r0/mozilla-central/objdir'
make[1]: *** [realbuild] Error 2
make[1]: Leaving directory`/media/DevDrive/poky/rpi-build/tmp/work/armv6-vfp-poky-linux-gnueabi/b2g-linuxgl-rpi/dev-r0/mozilla-central'
make: **\* [build] Error 2
ERROR: oe_runmake failed
ERROR: Function failed: do_compile (log file is located at /media/DevDrive/poky/rpi-build/tmp/work/armv6-vfp-poky-linux-gnueabi/b2g-linuxgl-rpi/dev-r0/temp/log.do_compile.14183)

**Comment by arky** [comment]
Full logs are here http://pastebin.mozilla.org/2708795

**Comment by arky** [comment]
Upstream bug: https://bugzilla.mozilla.org/show_bug.cgi?id=898905
